# Generated by Django 5.1 on 2024-08-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_usermodel_usermodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='date_created',
        ),
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ai_model_reply', models.CharField(max_length=7000)),
                ('user_query', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodels')),
            ],
        ),
    ]
