# Generated by Django 5.1 on 2024-08-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_messagemodel_date_created_conversationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmodel',
            old_name='date_created',
            new_name='date_queried',
        ),
    ]
