# Generated by Django 5.1 on 2024-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_created_conversationmodel_date_queried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmodel',
            name='date_queried',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
