# Generated by Django 5.1 on 2024-08-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_conversationmodel_date_queried'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('water', 'Water')], max_length=50)),
                ('reported_count', models.IntegerField(default=0)),
                ('escalated_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodels')),
            ],
        ),
    ]
