# Generated by Django 5.1 on 2024-09-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_issuereported'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='usermodels',
            name='tenant_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TicketsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=45, unique=True)),
                ('ticket_status', models.CharField(choices=[('PENDING', 'Pending'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('issue_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.issuereported')),
                ('tenant_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodels')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminModel',
        ),
    ]
