# Generated by Django 5.1 on 2024-09-12 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantmodel_usermodels_tenant_to_ticketsmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsmodel',
            name='issue_reported',
        ),
        migrations.RemoveField(
            model_name='ticketsmodel',
            name='ticket_status',
        ),
        migrations.CreateModel(
            name='TicketsStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=45, unique=True)),
                ('ticket_status', models.CharField(choices=[('PENDING', 'Pending'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('issue_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.issuereported')),
                ('tenant_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodels')),
            ],
        ),
    ]
