# Generated by Django 5.1 on 2024-09-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_ticketsmodel_issue_reported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=50)),
                ('appSecret', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('phoneNumberId', models.CharField(max_length=20)),
                ('accessToken', models.CharField(max_length=243)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantmodel')),
            ],
        ),
    ]
