# Generated by Django 5.1 on 2024-09-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_facebookcredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsmodel',
            name='tenant_to',
        ),
        migrations.RemoveField(
            model_name='ticketsstatusmodel',
            name='issue_reported',
        ),
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='issue',
            field=models.CharField(choices=[('water', 'Water')], default='water', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketsstatusmodel',
            name='ticket_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ticketsmodel'),
        ),
    ]
