# Generated by Django 5.1 on 2024-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_ticketsmodel_tenant_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='comments',
            field=models.CharField(default='no comments added till now to the ticket if added will be displayed', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='date_reported',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
