# Generated by Django 5.1 on 2024-09-21 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_ticketsstatusmodel_date_reported'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcredentials',
            name='phoneNumberId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
