# Generated by Django 5.1 on 2024-09-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_facebookcredentials_phonenumberid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
