# Generated by Django 5.1 on 2024-09-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usermodels_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ticketsstatusmodel',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.issuemodel'),
        ),
    ]
