# Generated by Django 5.1 on 2024-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_issuemodel_alter_ticketsstatusmodel_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
