# Generated by Django 5.1 on 2024-09-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_issuemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsmodel',
            name='Description',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
    ]
