# Generated by Django 5.1 on 2024-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_ticketsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='description',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
    ]
