# Generated by Django 5.1 on 2024-10-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_templatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketsstatusmodel',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.issuemodel'),
        ),
    ]
