# Generated by Django 5.1 on 2024-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_templatemodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmodel',
            name='date_queried',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
