# Generated by Django 5.1 on 2024-10-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_conversationmodel_date_queried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookcredentials',
            name='appSecret',
        ),
    ]
