# Generated by Django 5.1 on 2024-10-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_facebookcredentials_appsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='commentHistory',
            field=models.CharField(default='  ', max_length=150000),
            preserve_default=False,
        ),
    ]
