# Generated by Django 5.1 on 2024-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_ticketsstatusmodel_commenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsstatusmodel',
            name='commentHistory',
            field=models.CharField(max_length=15000),
        ),
    ]
