# Generated by Django 5.1 on 2024-11-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_dashboardaccessprovidedbyclientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
