# Generated by Django 5.1 on 2025-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_conversationmodel_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmodel',
            name='address',
            field=models.CharField(default='none:', max_length=2000),
            preserve_default=False,
        ),
    ]
