# Generated by Django 5.1 on 2025-01-30 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_tenantmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOptionsToTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=26)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantmodel')),
            ],
        ),
    ]
