# Generated by Django 5.1 on 2025-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_chatoptionstotenant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantmodel',
            name='address',
        ),
        migrations.AddField(
            model_name='usermodels',
            name='address',
            field=models.CharField(default=' not provided', max_length=2000),
            preserve_default=False,
        ),
    ]
