# Generated by Django 5.1 on 2025-01-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_tenantmodel_address_usermodels_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='issue',
            field=models.CharField(default='other issues', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatoptionstotenant',
            name='options',
            field=models.CharField(max_length=24),
        ),
    ]
