# Generated by Django 5.1 on 2025-02-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_ticketsstatusmodel_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
