# Generated by Django 5.1 on 2025-02-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_usermodels_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsmodel',
            name='image_path',
            field=models.CharField(default='no image is provided', max_length=500),
            preserve_default=False,
        ),
    ]
