# Generated by Django 5.1 on 2025-02-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_ticketsmodel_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsmodel',
            name='image_path',
        ),
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
