# Generated by Django 5.1 on 2025-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_assignemodel_ticketsstatusmodel_assigne'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignemodel',
            name='email',
            field=models.CharField(default='e', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
