# Generated by Django 5.1 on 2025-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_assignemodel_email_alter_usermodels_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsstatusmodel',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
