# Generated by Django 5.1 on 2025-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_ticketsstatusmodel_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsstatusmodel',
            name='date_reported',
            field=models.DateField(auto_now_add=True),
        ),
    ]
