# Generated by Django 5.1 on 2025-03-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_ticketsstatusmodel_date_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsstatusmodel',
            name='feedback',
            field=models.CharField(default='feedback is not provided by the user', max_length=100),
            preserve_default=False,
        ),
    ]
